[deploy]
startCommand = "v2ray run -config /etc/v2ray/config.json"

[[services]]
name = "v2ray"
port = 8080

[[services.ports]]
handler = "http"
port = 8080

[[services.ports]] 
handler = "ws"
port = 8080
